# Generated by Django 3.2.12 on 2022-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="age",
            field=models.PositiveIntegerField(blank=True, verbose_name="возраст"),
        ),
    ]
